server:
  port: 8090
spring:
  application:
    name: satellite
  datasource:
    url: jdbc:mysql://localhost:3306/satellite_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
file:
  storage:
    base-path: ./data/images

baidu:
  map:
    ak: "mpG23F6H4Hx4ZH7RQxpOKpNXfgH86zOY"